Chore: Refactor using redata-commons
UAL-RE/ReQUIAM pull request #146
Opened 2021-04-12 19:21 UTC by astrochun

**Description**

This PR uses `redata` commons sub-package and deprecates redundant code.

Commit history:

- Add redata to requirements.txt
- Use redata.commons.logger
- Use redata.commons.git_info

See #145

**ToDo List**

 - [ ] Update production environment for redata dependency

**Test plan**

 - Unit tests have passed
 - Local testing needed

**Update Changelog**

- [ ] README.md, [changelog](../../README.md#changelog) 

*Resources*

*Screenshots or additional context*

2021-04-12 19:32 UTC, astrochun reviewed
Changes look good.

2021-04-15 16:25 UTC, damian-romero requested changes
The code looks good.

As in ReQUIAM_csv, I wonder if this should be labeled as a `chore` or not, and you may or may not want to update the `redata` package version, considering that the only update was documentation-related.

2021-04-19 16:47 UTC, astrochun commented
> The code looks good.
> 
> As in ReQUIAM_csv, I wonder if this should be labeled as a `chore` or not, and you may or may not want to update the `redata` package version, considering that the only update was documentation-related.

Same situation here. This is a technical debt reduction.

2021-04-19 18:55 UTC, damian-romero approved these changes

2021-04-19 19:03 UTC, merged