Update README.md
UAL-RE/ReQUIAM pull request #163
Opened 2022-01-22 01:33 UTC by yhan818

Updated Python version required and other

2022-01-24 18:28 UTC, zoidy requested changes
See suggestion in the file

2022-01-24 18:28 UTC, zoidy commented on README.md
> +1. Python (>=3.7) ((originally stated "3.7.9", it ran at "3.7.5". My local machine runs 3.8.8)
For cleanliness, recommend moving the comment to the pull request message instead.
```suggestion
1. Python (>=3.7) 
```

2022-01-25 18:48 UTC, yhan818 reviewed
Looks good

2022-01-26 03:25 UTC, zoidy approved these changes

2022-01-26 03:25 UTC, merged