Update README.md
UAL-RE/ReQUIAM pull request #165
Opened 2022-04-25 23:15 UTC by yhan818

updated README for configuring python and running env by identifying a few typos / discrepancies (conda). updated parameters "--portal" "--quota"

2022-04-26 14:14 UTC, zoidy requested changes
Thanks for the updates, the changes add some nice points of clarification. Overall, I recommend keeping the docs clean and concise. See the specific comments in my review

2022-04-26 14:14 UTC, zoidy commented on README.md
> +(figshare_patrons) $ python setup.py develop (this is to setup all the necessary packages for this package. Without them, you cannot run. if you see errors, check python PATH. You may consider to add
Recommend keeping docs clean and avoiding redundant info (e.g., any dev should know that setup.py is supposed to install all the dependencies.). Also, I recommend explaining why and when one might want to use the psudo function you describe

2022-04-26 14:14 UTC, zoidy commented on README.md
> +Note: These packages must be installed correctly so that the script can run.
Recommend keeping docs clean and avoiding redundant info

2022-04-26 14:14 UTC, zoidy commented on README.md
> +flag options, such as `--ldap_password`.  To getting access to `***override***`, ask the system administrator
getting -> get

2022-04-26 14:14 UTC, zoidy commented on README.md
> +Setuping env variables for the script to run
Setuping -> setup

2022-04-26 14:14 UTC, zoidy commented on README.md
> +To execute the script and update Grouper and EDS, include the `portal`, `quota`command-line flags:
Add space between `quota` and command-line.

2022-04-26 14:14 UTC, zoidy commented on README.md
> +using "--sync" will execute the script!!!
using -> adding

2022-04-26 14:14 UTC, zoidy commented on README.md
>  indicate what Grouper updates will occur.
Lines 185-187. Recommend keeping docs clean and avoiding redundant info. This same information is repeated above

2022-04-26 14:14 UTC, zoidy commented on README.md
> +(figshare_patrons) $ git clone https://github.com/UAL-RE/ReQUIAM.git   (this is to clone a copy of the project to local directory)
Recommend keeping docs clean and concise. I.e., Any developer should know what `git clone` does

2022-04-27 00:26 UTC, yhan818 reviewed
Please review after the updates.

2022-04-27 01:58 UTC, zoidy approved these changes
looks good thanks!

2022-04-27 20:13 UTC, merged