issue 170. update to python 3.9
UAL-RE/ReQUIAM pull request #171
Opened 2022-06-27 19:10 UTC by yhan818

2022-06-28 19:58 UTC, zoidy requested changes
On the change to setup.py: I think we're setting ourselves up for confusion if we start mixing changes to version numbers in with pull requests for other changes. Recall that version updates follow a workflow that involves other changes as well. What do you think about doing the version updates in a separate PR?

2022-06-28 20:33 UTC, yhan818 commented
> On the change to setup.py: I think we're setting ourselves up for confusion if we start mixing changes to version numbers in with pull requests for other changes. Recall that version updates follow a workflow that involves other changes as well. What do you think about doing the version updates in a separate PR?

Sure. We can do that. Let me change back "setup.py" and create another PR.

2022-06-29 19:04 UTC, zoidy approved these changes

2022-06-29 19:04 UTC, merged

2022-06-29 19:15 UTC, zoidy commented
Ref: #170