Issue 177. Upgrade to v1.1.0
UAL-RE/ReQUIAM pull request #179
Opened 2022-07-08 21:15 UTC by yhan818

**Description**

This pull request updates ReQUIAM v1.01.1 -> v1.1.0

**Update Changelog**

- [ ] [changelog](../../blob/master/CHANGELOG.md)

**Bump version**

- [ ] [`README.md`](../../blob/master/README.md) (if needed)
- [ ] [`setup.py`](../../blob/master/setup.py)
- [ ] [`requiam/__init__.py`](../../blob/master/requiam/__init__.py)
- [ ] ReadTheDocs [`conf.py`](../../blob/master/docs/source/conf.py)
- [ ] ReadTheDocs [`getting_started.rst`](../../blob/master/docs/source/getting_started.rst)
- [ ] ReadTheDocs [`requirements.txt`](../../blob/master/docs/requirements.txt)

*Update Additional Documentation*
- [ ] [ReadTheDocs files](../../blob/master/docs/source/). Check and update the appropriate sections in the .rst files as needed

*Screenshots or additional context*

2022-07-08 23:59 UTC, yhan818 commented
Build is successful. https://requiam--179.org.readthedocs.build/en/179/

2022-07-11 19:01 UTC, zoidy requested changes
Thank you, let's revert the change to the configuration figshare.ini and make it it's own separate PR. It isn't related to #177. Also in future developers might appreciate descriptive commit messages. I had to click each commit within the PR to find which one had changed figshare.ini since they are all called "Issue 177. Upgrade to v1.1.0"

2022-07-12 06:01 UTC, yhan818 commented
> 



> Thank you, let's revert the change to the configuration figshare.ini and make it it's own separate PR. It isn't related to #177. Also future developers might appreciate descriptive commit messages. I had to click each commit within the PR to find which one had changed figshare.ini since they are all called "Issue 177. Upgrade to v1.1.0"

Sounds good. I will make another PR after merging this.

2022-07-12 14:03 UTC, zoidy approved these changes

2022-07-12 14:03 UTC, merged