v1.1.1
UAL-RE/ReQUIAM pull request #188
Opened 2024-01-06 05:49 UTC by yhan818

Click the `Preview` tab and select a PR template:

- [Release](?expand=1&template=release-pull-request.md)
v1.1.1

- [Bug fix](?expand=1&template=bug-pull-request.md)
Issue #186

2024-01-06 18:43 UTC, zoidy requested changes
- Changelog.md looks good
- Need to bump the version number in the code
- The v1.1.1 tag was created before this PR was merged. This triggered the GitHub action to generate a new release without the  changes contained in this PR. Please delete that release and re-create it once this PR is merged

2024-01-09 05:11 UTC, yhan818 commented
removed the v1.1.1 tag and did a new pull request.

2024-01-09 15:12 UTC, zoidy requested changes
Thank you for removing the tag. The version in the code still needs to be updated. Remember we have to update __init__.py. Refer to the [release commit](https://github.com/UAL-RE/ReQUIAM/commit/19367bf49064a67e47a83dcfaa5468695f7dcf3e#diff-fd4b3ff63f236fcfae6e7e1e896a3ee3c216618cdc1b91c901801dc704557888) you did a while ago as an example

2024-01-10 14:26 UTC, zoidy approved these changes

2024-01-11 01:30 UTC, merged